# --source={/single/folder/path, overwrites the default configured here}
# This is an array of folders to search for files you want to rename.
# For Windows paths, make sure you escape the path with a \, for example: "D:\\Downloads".
# For *nix, use standard path, for example: "/path/to/folder".
source_dirs:
  - '/Volumes/Films/#new'

# Destination paths, e.g. "/Volumes/Films/HD". If you don't want to sort by quailty, just
# set the value for `default` and remove the rest. Value quality sort properties are:
# "720p", "1080p", "4K", "SD", and "default".
# Fylm works best if the source and destination are on the same partition, otherwise files end up being copied, which can take a long time.
destination_dirs:
  720p: /Volumes/Films/HD
  1080p: /Volumes/Films/HD
  2160p: /Volumes/Films/4K
  SD: /Volumes/Films/SD
  default: /Volumes/Films/#new

# Template pattern for renaming files.
# Valid template objects: {title}, {title-the}, {year}, {edition}, {quality}, {quality-full}
# If you want to add characters with pattern objects, place them inside {} e.g. { - edition}.
# For escaping templating delimiters, use \{ \}, e.g. {|{edition\}}.
rename_pattern: 
  file: '{title} {(year)} {[edition]} {quality-full} {hdr}'
  folder: '{title} {(year)}'

# Sort files into individual subfolders when moving them, e.g. /Volumes/Films/HD/The Last Starfighter (1984)/{files go here}.
# If set to false, all files are added to the main destination folder, and the folder rename_pattern above is ignored.
use_folders: true

# Remove unwanted files from source folders after the important files have been copied.
remove_unwanted_files: true

# Remove the original source subfolder left behind after the important files have been copied, as long as it is not the root source dir.
remove_source: true

# Ignore video files or dirs smaller than this size, in MB. Good for skipping poorly named samples, tiny files, or empty dirs.
min_filesize:
  720p: 50
  1080p: 100
  2160p: 200
  SD: 20
  default: 20

# Use KiB, MiB, and GiB (multiples of 1024) when calculating file sizes.
# Set to false to use KB, MB, and GB (multiples of 1000)
size_units_ibi: true

# Path Where history.log will be written.
log_path: ./

# --hide-bad
# Hide bad films from the console output.
hide_bad: true

# --interactive
# Prompt to confirm or correct TMDb matches.
interactive: false

# --test 
# Write to the console as if moving/renaming/removing files but does not actually make changes.
test: false

# --debug
# Write advanced debugging details to the console.
debug: false

# Show runtime errors in the console
# TODO: Convert this to error_level
errors: true

# --no-console
# Do not write any information to console or stdout.
no_console: false

# --plaintext
# Output to the console without pretty formatting.
plaintext: false

# --rename
# Rename files and folders in place without moving or copying them.
rename_only: false

# --no-strict (disable)
# Use intelligent string comparison algorithm to ensure titles are properly matched.
# If your titles are accurate (parsable), this is the safest way to go, and results in the most
# accurate matching. Turning strict mode off will take the first match from TMDb even if the titles don't match.
strict: true

# Cache TMDb responses for faster loading.
cache: true

# Cache time-to-live, in hours.
cache_ttl: 168

# --limit={int, 0 = no limit}
# Limits the number of files that are checked/renamed in a single run. Useful for doing large rename jobs, 
# where you want to manually check matches with --test before performing destructive changes.
limit: 0

# --force-lookup
# DANGER ZONE
# This options disables the intelligent file/folder check that ensures they appear to be film-like 
# in name (e.g. have a year, valid filetype, and are not a TV show) before we look them up. Every file and folder
# will be checked in the source folders (except TV shows) which not only takes longer, but could find some 
# false-positive results. Best to test first before running.
force_lookup: false

# Duplicate checking can scan your destination folders for copies of the same film or file, and allows
# you to conditionally upgrade, replace, or ignore duplicates.
duplicates:

  # --no-duplicates
  # Enables duplicate checking
  enabled: true

  # --overwrite
  # DANGER ZONE
  # When duplicate checking is DISABLED, this will forcibly (and silently) overwrite ANY 
  # file (or matching files inside a film folder) with the identical name. Recommend using test mode
  # first before running if duplicate checking is disabled.
  # When duplicate checking is ENABLED, upgrading is handled by duplicate logic, but enabling 
  # this will force smaller files to overwrite larger files when the filenames are identical.
  force_overwrite: false

  # Enables upgrading of duplicates based on the upgrade table
  automatic_upgrading: true

  # For each resolution, identify which (if any) other resolutions are allowed to upgrade it.
  # Media is not factored in here, but lower-quality media will be automatically upgraded - 
  # for example, a 1080p Bluray will always upgrade a 1080p WEB-DL.
  # Size is also not factored here, but a smaller-size film will always upgrade a larger-size
  # film if the quality, media, resolution, and edition match.
  upgrade_table: 
    2160p: [] # Never upgrade or replace 2160p
    1080p: [] # Never upgrade or replace 1080p
    720p: ['1080p'] # 720p can be replaced with a 1080p file, but not a 2160p copy
    SD: ['1080p', '720p'] # SD or unknown can be upgraded by a 1080p or a 720p copy

  # When comparing films for upgrading, treat different editions as if they are the same film
  # If false, edition must match to be considered eligible for upgrading.
  ignore_edition: false

# Copy files to the destination instead of move, even if source and destination are on the 
# same partition. Copy will always be used when the source and destination are on different 
# partitions (or network).
always_copy: false

# --quiet
# Do not send notifications or update Plex
quiet: false

tmdb:

  # By default, this app looks up and matches film titles from TMDb. 
  # Setting 'enabled' to false will turn off the TMDb lookup service, and use best-guess offline cleanup of filenames.

  # You will need an API key to The Movie Database to access the API. To obtain a key, follow these steps:
  #  1. Register for, and verify, an account at https://www.themoviedb.org
  #  2. Select the API section on left side of your account page.
  #  3. Click on the link to generate a new API key and copy it here.
   
  # API reference docs: https://www.themoviedb.org/documentation/api
  enabled: true

  # TMDb API Key
  key: c49a08b548641c4954b3b84a5ae018c8

  # Percentage similarity (from 0.0 - 1.0) that a title retrieved from TMDb should be to the original.
  # Adjust this value as needed to find correct matches, but test first to check for incorrect matches.
  # Can be disabled on the fly by setting strict-mode to false or using --strict=no.
  min_title_similarity: 0.4

  # Difference in years between lookup year and TMDb results to still consider a valid match, as 
  # long as the titles match.
  max_year_diff: 1

  # --pop={float}
  # Minimum popularity ranking on TMDb to consider a valid match.
  # Popular titles generally rank above 10, though some obscure ones rank between 1 and 2
  min_popularity: 0.8

  # Films with this popularity value or higher are more likely to be considered a positive match.
  popular_threshold: 10

plex:

  # If you run a Plex server, you may want to notify it when new files are added. Configure your Plex
  # details here. 
  
  # You'll need a Plex token in order to do this. To obtain a key, follow these steps:
  #  1. Launch Plex and log in
  #  2. From any item in your library, click the ••• icon, and select 'Get Info'
  #  3. At the bottom of the inspector panel, click "View XML"
  #  4. In the new tab that opens (with the raw XML data), inspect the URL, and look for 'X-Plex-Token' in the URL.
  #  5. Copy that value into the 'token' property below.
   
  # For more help, see: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
  enabled: true

  # Plex base URL including port, e.g. http://127.0.0.1:32400
  baseurl: 'http://127.0.0.1:32400'

  # Plex token
  token: YOUR_KEY_HERE

  # Sections to notify to check for updates, e.g. - Movies
  sections:
    - Movies

pushover:

  # Pushover will receive a notification when films have been processed.
  enabled: true

  # Pushover app token, obtained from https://pushover.net/apps
  app_token: 'YOUR_APP_TOKEN_HERE'

  # Pushover user key, obtained from https://pushover.net
  user_key: 'YOUR_USER_KEY_HERE'

# An array of tuples containing period-separated words or regular expressions that match special editions.
# The second element in the tuple is the re-formatted/prettified 'edition' string.
# Order matters here: the first full match will be used, e.g. "extended.edition" will match before "extended".
# Always separate with '.' because these will be compiled into regular expressions.
edition_map: [
  ["(disney.)?classics.timeless.collection", "Disney Classics Timeless Collection"],
  ["extended.director.?s.cut", "Extended Director's Cut"],
  ["extended.remastered", "Extended Remastered"],
  ["extended.edition", "Extended Edition"],
  ["(dc|director.?s.cut).remastered", "Director's Cut Remastered"],
  ["(\\d+)th.a(nniversary)?.ed?(ition)?", "\\1th Anniversary Edition"],
  ["(\\d+)th.anniv(ersary)?", "\\1th Anniversary"],
  ["extended.collector.?s.edition", "Extended Collector's Edition"],
  ["collector.?s.edition", "Collector's Edition"],
  ["se.remastered", "Special Edition Remastered"],
  ["unrated.director.?s.cut", "Unrated Director's Cut"],
  ["director.?s.definitive.edition", "Director's Definitive Edition"],
  ["(dc|director.?s.cut|dircut)", "Director's Cut"],
  ["unrated.extended.cut", "Unrated Extended Cut"],
  ["(uce|ultimate.collectors.edition)", "Ultimate Collector's Edition"],
  ["ultimate.expanded.edition", "Ultimate Expanded Edition"],
  ["mind.bending.ed(ition)?", "Mind Bending Edition"],
  ["ultimate.ed(ition)?", "Ultimate Edition"],
  ["signature.ed(ition)?", "Signature Edition"],
  ["expanded.ed(ition)?", "Expanded Edition"],
  ["unrated.extended", "Unrated Extended"],
  ["unrated.remastered", "Unrated Remastered"],
  ["theatrical.remastered", "Theatrical Remastered"],
  ["alternate.ending", "Alternate Ending"],
  ["special.edition", "Special Edition"],
  ["theatrical.cut", "Theatrical Cut"],
  ["the.first.cut", "The First Cut"],
  ["final.cut", "Final Cut"],
  ["extended.cut", "Extended Cut"],
  ["remastered", "Remastered"],
  ["extended", "Extended"],
  ["the.richard.donner.cut", "The Richard Donner Cut"],
  ["the super duper cut", "The Super Duper Cut"],
  # Uncut, as long as it isn't preceded "Longer & "
  ["(?<!(longer\\W{3}))uncut", "Uncut"],
  ["unrated", "Unrated"],
  ["limited", "Limited"],
  ["theatrical", "Theatrical"],
  ["noir", "Noir"]
]

# Strip these strings from the beginning of titles (case insensitive). 
# Sometimes files are prefixed with tags, and we don't want to include them in the tmdb search or match.
strip_prefixes:
  - ams-
  - flame-
  - blow-
  - geckos-
  - rep-
  - pfa-
  - snow-
  - refined-
  - japhson-
  - sector7-

# If any of these strings are found (case insensitive) in a filename, the entire file will be ignored.  
# A word of caution: adding common words here (especially words found in titles) will result in files/folders
# being (unexpectedly) skipped.
ignore_strings:
  - fylmignore

# keep_period: Array of strings that should retain the period in the name when searching, e.g. L.A. or S.W.A.T.
keep_period:
  - L.A.
  - S.W.A.T.
  - After.Life
  - E.T.
  - D.A.R.Y.L.
  - B.C.
  - A.I.
  - G.I.

# Words in this list will remain uppercase
# Because this is a regular expression, we can support movie titles like 'IT'
always_upper:
  - TRON
  - RV
  - ^IT$
  - BFG
  - WALL·E

# Array of valid video filetypes
video_exts:
  - .mkv
  - .m4v
  - .mp4
  - .avi

# Array of additional filetypes to move and rename with films, e.g. srt, nfo    
extra_exts:
  - .srt