language: python

dist: xenial

python:
  # - "3.5"
  # - "3.6"
  # - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt --force
  - pip install -r requirements-test.txt --force

script:
  - cd fylm; pwd; pytest -xq tests/test_operations.py

notifications:
  email:
    on_success: change
    on_failure: change