language: python

dist: trusty

python:
  - "3.5"
  - "3.6"

install:
  - python setup.py install
  - pip install -r requirements-test.txt

script:
  - cd fylm; pytest -xq

notifications:
  email:
    on_success: change
    on_failure: change