language: python

dist: trusty

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - cd fylm; pytest -xq

notifications:
  email:
    on_success: change
    on_failure: change