language: python

dist: xenial

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt --force
  - pip install -r requirements-test.txt --force

script:
  - pytest -xvs

notifications:
  email:
    on_success: change
    on_failure: change